aplicaciones/carrito/urls.py
from django.conf.urls import url
from .views import *
# from django.views.static.
urlpatterns = [
    url(r'^agregar_carrito_compra/(?P<slug>[^/]+)/$', agregar_curso_carrito, name='p_agregar_compra'),
    url(r'^ver_carrito/(?P<usuario>[^/]+)$', ver_carrito, name='p_ver_carrito'),
]

carrito_compra/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from aplicaciones.usuarios.views import LogOut, userlogin
from aplicaciones.cursos.views import Index_principal
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index_principal.as_view(), name='p_index_principal'),
    url(r'^iniciar/$', userlogin, name="iniciar_sesion"),
    url(r'^salir/$', LogOut, name='cerrar_sesion'),
    url(r'^carrito/', include('aplicaciones.carrito.urls', namespace='app_carrito')),
    url(r'^cursos/', include('aplicaciones.cursos.urls', namespace='app_cursos')),
    url(r'^usuarios/', include('aplicaciones.usuarios.urls', namespace='app_usuarios')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static from staticfiles %}
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}Carrito{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %} ">
                <!-- icon font -->
        <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">

    </head>
    <body>
        {% include 'messages.html' %}
        {% include 'header.html' %}
        {% block contenido %}{% endblock %}
       <script src="{% static "js/jquery-3.2.1.slim.min.js" %}" ></script>
       <script  src=" {% static "js/popper.min.js" %} "></script>
       <script  src=" {% static "js/bootstrap.min.js" %} "></script>
    </body>
</html>

templates/header.html
   {% load static %} 
   {% load filtros_carrito %}
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/"> <span class="fa fa-home"></span> CARRITO DE COMPRAS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        </ul>
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
           <a class="nav-link star_icon" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="notification_count"></span><i class="fa fa-shopping-cart fa-lg star_icon" aria-hidden="true"></i></a>
           <div class="dropdown-menu dropdown-menu-right dimenc" aria-labelledby="navbarDropdownMenuLink">
              <div class="row">
                 <p class="mensaje_carrito"><strong>Tienes {{request.user|cantidad_cursos_carrito }} curso en tu carrito</strong></p>
              </div>
              {% for curso_carrito in request.user|cursos_carrito  %}
              <div class="container scroll_carrito">
              {% for curso in curso_carrito.cursos.all %}              
                <div class="row">
                  <div class="col-md-3 car_marg1">
                    <img class="img-cart" src=" {{curso.portada.url}} " alt="" height="59" width="50">
                  </div>
                  <div class="col-md-6 car_marg2">
                  <a href="#">  <p class="parrafo1">{{ curso.nombre }}</p></a>
                  </div>
                  <div class="col-md-3 car_marg">
                          <div class="row">
                             <div class="col-md-12 text_carrit">
                                <i class="fa fa-times left_text" aria-hidden="true"></i>
                             </div>
                             <div class="col-md-12 text_carrit">
                                <span class="left_text"><strong>{{curso.costo}}</strong></span>
                             </div>
                          </div>
                  </div>
                </div>
              {% endfor %}
              </div>
              {% endfor %}
              <div class="container pie_cart">
                   <div class="row grupo_cart">
                   <div class="col-md-6">
                     <span class="subti_cart"><strong>Total: </strong></span>
                   </div>
                   <div class="col-md-6 text_carrit1">
                     <span class="precio_cart"><strong>S/ {{request.user|costo_total_cursos}}</strong></span>
                   </div>
              </div>
              <div class="row ">
                     <div class="col-md-6">
                         <a href=" {% url 'app_carrito:p_ver_carrito' request.user.usuario %} "> <button type="button" class="btn btn-outline-info waves-effect ir_carrito">Ir a tu carrito</button></a>
                     </div>
              </div>
              </div> 
           </div>
        </div>
        {% endif %}
        <li class="form-inline my-2 my-lg-0">
          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <a  href=" {% url 'cerrar_sesion' %}" class="nav-link"><li class="nav-item active"> Bienvenido {{request.user}} <i class="fa fa-sign-in"> Cerrar sesión</i></a>
            </ul>
          </li>
          {%else%}
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active"><a href=" {% url 'iniciar_sesion' %} " class="nav-link"><i class="fa fa-sign-in" aria-hidden="true"> Iniciar sesión</i></a></li>
          </ul>
          {% endif %}
      </div>
    </nav>
         
          

templates/index.html
{% extends "base.html" %}
{% load filtros_carrito %}
{% block title %} Pagina de inicio | Carrito de Compras{% endblock title %}
{% block contenido %}
	<div class="row">
	        <div class="col-md-2 ">
	        	<h2>h </h2>
	        </div>
	</div>

    <div class="container">
    	<br>
		<h3>Agregar Cursos al Carrito</h3>
       <div class="row justify-content-center row-cur">
        {% for curso in cursos  %}
        <div class="col-md-4 col1">    
            <div class="card">

                <div class="view overlay hm-white-slight">
                    <img src=" {{curso.portada.url }} " class="img-fluid" alt="" width="300px" height="300px">
                    <a href="#">
                        <div class="mask"></div>
                    </a>
                </div>
        
                <!--content-->
                <div class="card-body">
                    <!--Title-->
                    <a href="#"><h4 class="card-title">{{curso.nombre}}</h4></a>
                    <hr>
                    <!--Text-->
                    <p class="card-text">{{ curso.resumen}}</p>
                {% if not curso.es_gratis %}
                {% if curso|si_agrego_curso_carrito %}
                  <a href="" class="btn btn-success"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Agreado</a> 
                    <a href=" {% url 'app_carrito:p_ver_carrito' request.user.usuario %} "> <button type="button" class="btn btn-outline-info waves-effect ir_carrito">Ir a tu carrito</button></a>
                  {% else %}  
                  <a href=" {% url 'app_carrito:p_agregar_compra' curso.slug %} " class="btn btn-primary"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Agregar al Carrito</a>  
                {% endif %}
                {% else %}
                <a href="#" class="btn btn-primary">Ingresar</a>
                {%endif%}

                </div>
                <!--content-->
                <!-- footer -->
                <div class="card-data">
                    <ul >
                        {% if curso.es_gratis %}
                        <span>Gratis</span>
                        {% else %}
                        <span>S/. {{curso.costo}}</span>
                        {% endif %}
                    </ul>
                </div>
                <!-- footer -->
            </div>
        </div>
        {% endfor %}     
        </div>
    </div>
{% endblock contenido %}

templates/messages.html
<div class="form-row justify-content-center">
  <div class="form-group col-md-4">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
        {{ message }} 
    </div>
    {%endfor%}

  </div>
</div>